services:
  db:
    image: postgres:16
    container_name: codeleap-db
    environment:
      POSTGRES_DB: codeleap
      POSTGRES_USER: codeleap
      POSTGRES_PASSWORD: 86707341-67a9-4bda-a360-082ca9b268c4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: codeleap-backend
    depends_on:
      - db
    environment:
      POSTGRES_DB: codeleap
      POSTGRES_USER: codeleap
      POSTGRES_PASSWORD: 86707341-67a9-4bda-a360-082ca9b268c4
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,backend:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: codeleap-frontend
    depends_on:
      - backend
    environment:
      API_TARGET: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
